### ISSUE TITLE
Build Issue : UglifyJs SyntaxError: Unexpected token: name

### ISSUE THREAD

**Issue by grempe** [staskjs/vue-resource-case-converter#1]
Using version 1.0.6 If I build my app, which I just recently added this plugin to, I see the following build error:

```
$ npm run build

> thesplit@1.0.0 build /Users/glenn/src/github/thesplit-vue
> cross-env NODE_ENV=production webpack --progress --hide-modules

Hash: 2b489f2de83e4914b8e1
Version: webpack 1.13.2
Time: 4367ms
       Asset     Size  Chunks             Chunk Names
    build.js  1.12 MB       0  [emitted]  main
build.js.map  1.39 MB       0  [emitted]  main

ERROR in build.js from UglifyJs
SyntaxError: Unexpected token: name (find) [./~/vue-resource-case-converter/src/vue-resource-case-converter.js:7,0]
```

If I comment out the import and registration of `vue-resource-case-converter` the build works fine.

```
// import VueResourceCaseConverter from 'vue-resource-case-converter'
...
// Vue.use(VueResourceCaseConverter)
...
```

Any thoughts?  I'd hate to have to pull this out, or do it manually in the response, (I just refactored my server to use snake_case is it should).

Here is the app that's failing (as of commit bfafb1fc47e255939c0ff7c3f6ed2b0ee949f753):

https://github.com/thesplit/thesplit-vue

**Comment by staskjs** [comment]
I shouldn't have used es6 version as main file, because usually node_modules is excluded from babel compilation. I changed main file to compiled one. Please update.

**Comment by grempe** [comment]
Works great now for me. Thanks!
