### ISSUE TITLE
Case conversion for keys with numbers

### ISSUE THREAD

**Issue by jeffsmohan** [staskjs/vue-resource-case-converter#2]
I've run into an issue with conversion between cases of keys that have numbers in them, given that there's no such thing as a capital number. For example: 

```
Snake-to-camel: 'account_email_2' -> 'accountEmail2'
Camel-to-snake: 'accountEmail2' -> 'account_email2'
```

Ideally, the `camelCase` and `snakeCase` functions would be perfect inverse functions, and `camelCase(snakeCase(x))` should always equate to `x`. (Non-inverse functions mean the back-and-forth communication with an API doesn't end up working, because you send back a different key than you received.) The functions are properly inverse if you only use `[a-z]` for names, but can't be true for `[0-9]` because numbers can't be capitalized. 

So we need to accept one of two not-perfectly-inverse compromises:

1. `snakeCase(camelCase('account_email_2')) -> 'account_email2'`
2. `snakeCase(camelCase('account_email2')) -> 'account_email_2'`

So this leads to a couple tricky design decisions. 

First, the library should choose which compromise to make by default. (Essentially, do we want APIs that use `foo_bar_2` or `foo_bar2` style to be broken by default. Currently, `foo_bar_2` is broken by default, but my recommendation would be to switch the default. My gut feel is more people use `foo_bar_2` style than `foo_bar2` style.) 

Second, ideally we could provide a method to "un-break" the version that's broken. This probably implies new configuration options for the library. A few flavors of this come to mind: 

1. Support custom case-conversion functions. `{camelCase: customFn, snakeCase: customFn}`
2. Support special-cased key conversions. `{customKeys: [['foo_bar_2', 'fooBar2'], ['baz3', 'baz_3']]}`
3. Support essentially a middleware layer to allow full manipulation of requests and responses.

Would you be open to a PR addressing this situation? And what would your thoughts be on the design decisions involved?

**Comment by staskjs** [comment]
Thank you for this issue.

I think that choosing one option over another in this case is not very obvious. It's like choosing between tabs and spaces. I personally prefer `foo_bar2` notion, but I won't be against another though.

Anyway I agree that we need some sort of customization. I would rather go with simple boolean parameter like `underscoreNumbers` that would switch to `foo_bar_2` style. Or the opposite if we decide to switch default. But I would have to change major version then.

Regarding customization options you offer:
1. There are not really much use for that in my opinion. Except you would like to introduce any other conversion. It won't hurt though.
2. This seems clumsy to me, but also won't hurt.
3. I don't see a point of it here, as there are only one use case for this interceptor.

Go on with PR.

**Comment by jeffsmohan** [comment]
I hear you on the tabs-vs-spaces thing. I agree, avoiding a breaking change in the package is worth just keeping things as they are, as far as default behavior. 

I'm happy to work up an implementation of an `underscoreNumbers` boolean option. It's certainly the simplest to implement and the easiest to work with. 

The only downside is that it doesn't give you the flexibility to be able to handle both conversions within the same Vue app. If you're working with multiple APIs, each of which uses a different convention, one of them would end up broken. 

Perhaps we could extend the existing `responseUrlFilter` and `requestUrlFilter` functionality to handle this well? We could continue to support the boolean return value from these functions, which would continue to work exactly the same as today. But we could also start to support a return value of an options hash:

```javascript
{
  convert: true,
  underscoreNumbers: true
}
```

This has a few benefits: it doesn't break any existing functionality, it gives a lot of flexibility to the user in handling weird edge cases, and it's a very extensible setup for the package in case there are more options we'd want to implement in the future. 

If we go this way, I'd recommend we also accept those same option parameters for ease and completeness sake on the base options object. Essentially, those would be global, and anything returned by the filter functions would be considered an override. 

```javascript
Vue.use(VueResourceCaseConverter, {
  convert: true,  // default true
  underscoreNumbers: false,  // default false to preserve existing functionality
  responseUrlFilter (url) {
    if (condition) {
      return {
        underscoreNumbers: true
      };
    }
  },
  requestUrlFilter (url) {
    if (condition) {
      return {
        underscoreNumbers: true
      };
    }
  }
});
```

What are your thoughts on this design?

**Comment by staskjs** [comment]
Good point on multiple APIs, it would require flexibility. I agree with your solution. Could you please update readme also?

**Comment by jeffsmohan** [comment]
Yup, sounds good! I'll get working on this, and have a pull request soon.

**Comment by staskjs** [comment]
Updated to version 2.1.0. Good job!

**Comment by jeffsmohan** [comment]
Thanks for your help, glad we could make this happen!
