### ISSUE TITLE
wrong conversion of properties when there is one capital letter

### ISSUE THREAD

**Issue by BartekZienkiewicz** [staskjs/vue-resource-case-converter#4]
I have an object, f.e.
`const data = { B: 'some text }`
and it's converted to:
`{ _b: 'some text' }`

Is there a chance to fix this? :)

**Comment by staskjs** [comment]
Do you expect it to leave as it is? Or to be lower case? I think lower case will be correct decision.

**Comment by BartekZienkiewicz** [comment]
IMO it should be as I declared

**Comment by staskjs** [comment]
Snake case usually comes in lower case... So I think I would make it lower case

**Comment by staskjs** [comment]
Done. Update to 2.1.1
